# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:chainguard-dev/libraries-malcontent-demo:.*
claim_pattern:
  job_workflow_ref: chainguard-dev/libraries-malcontent-demo/.github/workflows/scan-malware.yaml@.*

permissions:
  contents: write
  pull_requests: write
  workflows: write
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  packages: write
  id-token: write