# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:chainguard-dev/libraries-ultralytics-attack-demo:.*
claim_pattern:
  job_workflow_ref: chainguard-dev/libraries-ultralytics-attack-demo/.github/workflows/setup.yaml@.*

permissions:
  contents: write
  pull_requests: write
  issues: write
  workflows: write
