name: scan-malware

on:
  workflow_dispatch: # Allows manual triggering

env:
  MALCONTENT_IMAGE: "cgr.dev/chainguard/malcontent@sha256:fdfca44c401a5ca98af51292a821278644895bc1963f7a76a733d76647ff0ede"
  REPO_URL: "https://github.com/chainguard-dev/malcontent-samples.git"
  LOCAL_REPO_DIR: "malcontent-samples"
  ULTRALYTICS_SUBDIR: "python/2024.ultralytics"
  
jobs:
  scan-existing-image:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main

      - name: Clone malcontent-samples repo
        run: |
          if [ -d "${LOCAL_REPO_DIR}" ]; then
            echo "[*] Using existing local repo at ${LOCAL_REPO_DIR}"
          else
            echo "[*] Cloning repository (shallow)..."
            git clone --depth=1 --branch main --single-branch "${REPO_URL}" "${LOCAL_REPO_DIR}"
          fi

      - name: 'Pull Malcontent Image'
        run: |
          docker pull "${{ env.MALCONTENT_IMAGE }}"

      
      - name: Set up full path
        id: paths
        run: |
          FULLBASEPATH="${GITHUB_WORKSPACE}/${LOCAL_REPO_DIR}/${ULTRALYTICS_SUBDIR}"
          echo "FULLBASEPATH=$FULLBASEPATH"
          echo "fullpath=$FULLBASEPATH" >> "$GITHUB_OUTPUT"

      - name: Diff v8.3.40 ↔ v8.3.41
        run: |
          docker run --rm -v "${{ steps.paths.outputs.fullpath }}:/home/nonroot/malcontent/" \
            "${MALCONTENT_IMAGE}" diff \
            /home/nonroot/malcontent/v8.3.40 \
            /home/nonroot/malcontent/v8.3.41

      - name: Diff v8.3.41 ↔ v8.3.44
        run: |
          docker run --rm -v "${{ steps.paths.outputs.fullpath }}:/home/nonroot/malcontent/" \
            "${MALCONTENT_IMAGE}" diff \
            /home/nonroot/malcontent/v8.3.41 \
            /home/nonroot/malcontent/v8.3.44

      - name: Diff v8.3.44 ↔ v8.3.46
        run: |
          docker run --rm -v "${{ steps.paths.outputs.fullpath }}:/home/nonroot/malcontent/" \
            "${MALCONTENT_IMAGE}" diff \
            /home/nonroot/malcontent/v8.3.44 \
            /home/nonroot/malcontent/v8.3.46

      - name: Complete
        run: echo "[✔] Done."    
      # - name: Upload Grype SARIF results
      #   if: ${{ env.SCAN_WITH_GRYPE == 'true' }}
      #   uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3.28.11
      #   with:
      #     sarif_file: grype-results.sarif

      